# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20170802_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_proce',
            new_name='total_price',
        ),
    ]
