# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_productinorder_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_address',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
