# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20170805_1521'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryProduct',
            new_name='ProductCategory',
        ),
    ]
